image: archlinux

variables:
  GIT_SUBMODULE_STRATEGY: recursive

.common: &common
  script:
    - ./dependency_helper.sh
    - make -f Makefile.$PLATFORM
  artifacts:
    paths:
      - appstore.$EXT

PC:
  <<: *common
  variables:
    PLATFORM: pc
    EXT: bin

PC-sdl1:
  <<: *common
  variables:
    PLATFORM: pc-sdl1
    EXIT: bin

WiiU:
  <<: *common
  variables:
    PLATFORM: wiiu
    EXT: rpx

Switch:
  <<: *common
  variables:
    PLATFORM: switch
    EXT: nro

3ds:
  <<: *common
  variables:
    PLATFORM: 3ds
    EXT: 3dsx

Wii:
  <<: *common
  variables:
    PLATFORM: wii
    EXT: dol
