language: cpp

services:
  - docker

matrix:
  include:
    - env: PLATFORM=pc
    - env: PLATFORM=pc-sdl1
    - env: PLATFORM=wiiu
    - env: PLATFORM=switch
    - env: PLATFORM=3ds

script:
  - docker run -e PLATFORM="$PLATFORM"
               -v $(pwd):/code archlinux
               /bin/bash -c "cd /code && ./dependency_helper.sh && ./build.sh"
