language: cpp
sudo: required

os: linux
dist: xenial

cache:
  directories:
    - /home/travis/brewbins
    - /home/travis/downloads

env:
  global:
    - DEVKITPRO=/opt/devkitpro
    - DEVKITPPC=/opt/devkitpro/devkitPPC
    - WUT_ROOT=/opt/devkitpro/wut

matrix:
  include:
    - env: PLATFORM=buck
    - env: PLATFORM=switch
    - env: PLATFORM=wiiu
    - env: PLATFORM=pc
  allow_failures:
    - env: PLATFORM=switch
    - env: PLATFORM=wiiu
    - env: PLATFORM=pc

addons:
  apt:
    packages:
      - git
      - wget

install:
  - ./dependency_helper.sh

script:
  - ./build.sh
