language: cpp

services:
  - docker

matrix:
  include:
    - env: PLATFORM=pc
    - env: PLATFORM=switch
    - env: PLATFORM=wiiu

script:
  - docker run -e PLATFORM="$PLATFORM"
               -e DEVKITPRO="/opt/devkitpro"
               -e DEVKITPPC="$DEVKITPRO/devkitPPC"
               -e WUT_ROOT="$DEVKITPRO/wut"
               -v $(pwd):/code ubuntu:18.10
               /bin/bash -c "cd /code && ./dependency_helper.sh && ./build.sh"
