language: cpp

services:
  - docker

env:
  global:
    - DEVKITPRO=/opt/devkitpro
    - DEVKITPPC=/opt/devkitpro/devkitPPC
    - WUT_ROOT=/opt/devkitpro/wut

matrix:
  include:
    - env: PLATFORM=pc
    - env: PLATFORM=switch
    - env: PLATFORM=wiiu
  allow_failures:
    - env: PLATFORM=switch
    - env: PLATFORM=wiiu

script:
  - docker run -e PLATFORM="$PLATFORM"
               -e DEVKITPRO="$DEVKITPRO"
               -e DEVKITPPC="$DEVKITPPC"
               -e WUT_ROOT="$WUT_ROOT"
               -v $(pwd):/code ubuntu:18.10
               /bin/bash -c "cd /code && ./dependency_helper.sh && ./build.sh"
