manifest = "94ceaa7e6f37bf3db45f5313668f740704686e96e357beb4b0148070b98d1db9"

[[dependency]]
package = "gitlab.com/4tu/chesto"
target = "//:chesto"

[[dependency]]
package = "gitlab.com/4tu/libget"
target = "//:libget"

[lock."github.com/buckaroo-pm/madler-zlib"]
versions = [ "1.2.11" ]
revision = "94a70f3274f15bf98b472178e91fd57a6e6c53d8"

[lock."github.com/buckaroo-pm/mapbox-rapidjson"]
versions = [ "branch=master" ]
revision = "44ccecfb229c4862ef4fa924a4841749196abfc7"

[lock."github.com/buckaroo-pm/nmoinvaz-minizip"]
versions = [ "1.1.0" ]
revision = "2e9b639463f3483c761ea94a14b57a253425ee1f"

[lock."github.com/buckaroo-pm/pkg-config-curl"]
versions = [ "branch=master" ]
revision = "172dabe81beabe3f4dce71d66a5ff9251ef9ef11"

[lock."gitlab.com/4tu/chesto"]
versions = [ "branch=master" ]
revision = "023e4daa18e46e0c73ffe0d6e0dc7dbc87373ea4"

[lock."gitlab.com/4tu/libget"]
versions = [ "branch=master" ]
revision = "01d5d28c293b98800dee7460479f367ede8d62db"
